import { 
  GameState, 
  GameTable, 
  SyndicateStaff, 
  CasinoUpgrade, 
  FrontBusiness, 
  PrestigePerk,
  Tournament,
  SponsoredPro,
  Relic,
  District,
  Achievement,
  SportsbookMatch,
  BlackMarketContract,
  HeistMission,
  ShadowCabinetOfficial,
  WheelReward
} from './types';

export const INITIAL_TABLES: Record<string, GameTable> = {
  'underground-dice': {
    id: 'underground-dice',
    name: 'Cardboard Craps',
    category: 'Underground',
    description: 'Street dice rolled against a back-alley brick wall.',
    baseCost: 25,
    costMultiplier: 1.15,
    baseRevenue: 1.2,
    baseChips: 0.15,
    baseHeat: 0.08,
    iconName: 'Dices',
    accentColor: 'from-amber-600 to-yellow-500',
    level: 1, // Starts with 1 so player has initial income
    unlocked: true,
    unlockCost: 0,
  },
  'poker-den': {
    id: 'poker-den',
    name: 'Basement Poker Table',
    category: 'Underground',
    description: 'A smoke-filled private room with a worn green felt table.',
    baseCost: 600,
    costMultiplier: 1.16,
    baseRevenue: 6,
    baseChips: 0.8,
    baseHeat: 0.14,
    iconName: 'Gamepad2',
    image: '/images/table_poker.jpg',
    accentColor: 'from-emerald-600 to-green-400',
    level: 0,
    unlocked: false,
    unlockCost: 500,
  },
  'speakeasy-blackjack': {
    id: 'speakeasy-blackjack',
    name: 'Speakeasy 21',
    category: 'Speakeasy',
    description: 'Single-deck blackjack served behind a hidden bookshelf door.',
    baseCost: 10000,
    costMultiplier: 1.18,
    baseRevenue: 40,
    baseChips: 5,
    baseHeat: 0.30,
    iconName: 'Layers',
    accentColor: 'from-blue-600 to-cyan-400',
    level: 0,
    unlocked: false,
    unlockCost: 8500,
  },
  'chinatown-pai-gow': {
    id: 'chinatown-pai-gow',
    name: 'Chinatown Pai Gow Tiles',
    category: 'Speakeasy',
    description: 'Traditional 32-tile bone dominoes wagered in a subterranean tea parlor.',
    baseCost: 55000,
    costMultiplier: 1.19,
    baseRevenue: 110,
    baseChips: 14,
    baseHeat: 0.45,
    iconName: 'Layers',
    accentColor: 'from-red-600 to-amber-500',
    level: 0,
    unlocked: false,
    unlockCost: 45000,
  },
  'roulette-alley': {
    id: 'roulette-alley',
    name: 'Neon Roulette Wheel',
    category: 'Casino Floor',
    description: 'A polished mahogany single-zero wheel with high turnover.',
    baseCost: 180000,
    costMultiplier: 1.20,
    baseRevenue: 320,
    baseChips: 35,
    baseHeat: 0.65,
    iconName: 'CircleDot',
    image: '/images/table_roulette.jpg',
    accentColor: 'from-red-600 to-rose-400',
    level: 0,
    unlocked: false,
    unlockCost: 150000,
  },
  'red-dragon-sic-bo': {
    id: 'red-dragon-sic-bo',
    name: 'Red Dragon Sic Bo',
    category: 'Casino Floor',
    description: 'Three dice shaken under an illuminated glass dome with rapid betting action.',
    baseCost: 900000,
    costMultiplier: 1.21,
    baseRevenue: 950,
    baseChips: 110,
    baseHeat: 0.90,
    iconName: 'Dices',
    accentColor: 'from-amber-600 to-red-500',
    level: 0,
    unlocked: false,
    unlockCost: 750000,
  },
  'high-roller-holdem': {
    id: 'high-roller-holdem',
    name: "VIP Hold'em Sanctuary",
    category: 'Casino Floor',
    description: 'Where local mobsters and wealthy degenerates play uncapped pots.',
    baseCost: 4200000,
    costMultiplier: 1.22,
    baseRevenue: 2400,
    baseChips: 260,
    baseHeat: 1.30,
    iconName: 'Crown',
    accentColor: 'from-amber-500 to-yellow-300',
    level: 0,
    unlocked: false,
    unlockCost: 3500000,
  },
  'monte-carlo-chemin': {
    id: 'monte-carlo-chemin',
    name: 'Chemin de Fer Salon',
    category: 'Casino Floor',
    description: 'The classic European high-society card game where players wager against each other.',
    baseCost: 18000000,
    costMultiplier: 1.23,
    baseRevenue: 7500,
    baseChips: 800,
    baseHeat: 1.60,
    iconName: 'Gem',
    accentColor: 'from-blue-600 to-indigo-500',
    level: 0,
    unlocked: false,
    unlockCost: 15000000,
  },
  'high-limit-craps': {
    id: 'high-limit-craps',
    name: 'Riviera Golden Craps',
    category: 'Casino Floor',
    description: 'Polished walnut double-table with roaring shooters and diamond leather bumpers.',
    baseCost: 42000000,
    costMultiplier: 1.23,
    baseRevenue: 12000,
    baseChips: 1250,
    baseHeat: 1.90,
    iconName: 'Dices',
    accentColor: 'from-amber-500 to-yellow-300',
    level: 0,
    unlocked: false,
    unlockCost: 35000000,
  },
  'baccarat-penthouse': {
    id: 'baccarat-penthouse',
    name: 'Penthouse Baccarat',
    category: 'VIP Penthouse',
    description: 'Chilled champagne, silk tuxedos, and devastatingly high wagers.',
    baseCost: 90000000,
    costMultiplier: 1.24,
    baseRevenue: 20000,
    baseChips: 2000,
    baseHeat: 2.20,
    iconName: 'Gem',
    accentColor: 'from-purple-600 to-fuchsia-400',
    level: 0,
    unlocked: false,
    unlockCost: 75000000,
  },
  'caribbean-stud-lounge': {
    id: 'caribbean-stud-lounge',
    name: 'Caribbean Stud Oasis',
    category: 'VIP Penthouse',
    description: 'A tropical high-stakes five-card stud salon with an ever-growing progressive jackpot meter.',
    baseCost: 300000000,
    costMultiplier: 1.25,
    baseRevenue: 45000,
    baseChips: 4500,
    baseHeat: 2.60,
    iconName: 'Gamepad2',
    accentColor: 'from-teal-500 to-cyan-400',
    level: 0,
    unlocked: false,
    unlockCost: 250000000,
  },
  'macau-dragon-vip': {
    id: 'macau-dragon-vip',
    name: 'Macau Imperial Dragon',
    category: 'VIP Penthouse',
    description: 'Private salon for billionaire junket syndicates wagering eight-figure plaques.',
    baseCost: 780000000,
    costMultiplier: 1.25,
    baseRevenue: 95000,
    baseChips: 9000,
    baseHeat: 3.00,
    iconName: 'Crown',
    accentColor: 'from-emerald-500 to-gold',
    level: 0,
    unlocked: false,
    unlockCost: 650000000,
  },
  'cosmic-whale-salon': {
    id: 'cosmic-whale-salon',
    name: 'The Syndicate Vault',
    category: 'VIP Penthouse',
    description: 'An international invite-only salon. Fortunes are won in minutes.',
    baseCost: 1800000000,
    costMultiplier: 1.26,
    baseRevenue: 180000,
    baseChips: 16000,
    baseHeat: 3.50,
    iconName: 'Sparkles',
    accentColor: 'from-yellow-400 via-rose-500 to-indigo-600',
    level: 0,
    unlocked: false,
    unlockCost: 1500000000,
  },
  'elysium-high-limit': {
    id: 'elysium-high-limit',
    name: 'Elysium Gold Wheel',
    category: 'VIP Penthouse',
    description: 'Solid 24k gold roulette wheel operated by master croupiers under chandelier domes.',
    baseCost: 8000000000,
    costMultiplier: 1.27,
    baseRevenue: 550000,
    baseChips: 48000,
    baseHeat: 4.20,
    iconName: 'CircleDot',
    accentColor: 'from-gold to-amber-600',
    level: 0,
    unlocked: false,
    unlockCost: 6500000000,
  },
  'sovereign-salon': {
    id: 'sovereign-salon',
    name: 'Sovereign Diamond Salon',
    category: 'VIP Penthouse',
    description: 'Exclusive Monaco-tier private salon for oil barons and sovereign wealth funds.',
    baseCost: 42000000000,
    costMultiplier: 1.28,
    baseRevenue: 2200000,
    baseChips: 180000,
    baseHeat: 5.00,
    iconName: 'Crown',
    accentColor: 'from-cyan-500 to-blue-600',
    level: 0,
    unlocked: false,
    unlockCost: 35000000000,
  },
  'celestial-infinite-poker': {
    id: 'celestial-infinite-poker',
    name: 'Celestial Infinite Hold\'em',
    category: 'VIP Penthouse',
    description: 'Uncapped offshore cash game where the world\'s top hedge fund titans bet corporate equities.',
    baseCost: 220000000000,
    costMultiplier: 1.29,
    baseRevenue: 9500000,
    baseChips: 750000,
    baseHeat: 6.50,
    iconName: 'Sparkles',
    accentColor: 'from-fuchsia-500 to-purple-600',
    level: 0,
    unlocked: false,
    unlockCost: 180000000000,
  },
  'apex-reserve': {
    id: 'apex-reserve',
    name: 'The Apex World Reserve',
    category: 'VIP Penthouse',
    description: 'The ultimate gambling sanctum. Trillions wagered across offshore accounts with total secrecy.',
    baseCost: 1200000000000,
    costMultiplier: 1.30,
    baseRevenue: 45000000,
    baseChips: 3500000,
    baseHeat: 8.00,
    iconName: 'Sparkles',
    accentColor: 'from-rose-500 via-gold to-cyan-400',
    level: 0,
    unlocked: false,
    unlockCost: 1000000000000,
  },
  'omega-syndicate-core': {
    id: 'omega-syndicate-core',
    name: 'The Omega Syndicate Core',
    category: 'VIP Penthouse',
    description: 'The singularity of underworld empire wealth. Multi-trillion wagers managed by quantum ledger.',
    baseCost: 9500000000000,
    costMultiplier: 1.32,
    baseRevenue: 350000000,
    baseChips: 28000000,
    baseHeat: 12.00,
    iconName: 'Crown',
    accentColor: 'from-emerald-400 via-gold to-cyan-400',
    level: 0,
    unlocked: false,
    unlockCost: 8000000000000,
  },
};

export const INITIAL_STAFF: Record<string, SyndicateStaff> = {
  'dealer-sal': {
    id: 'dealer-sal',
    name: "Fast-Hands Sal",
    role: "Street Pit Boss",
    avatar: "/images/sal_avatar.jpg",
    description: "Knows how to roll bones without looking. Doubles Cardboard Craps revenue.",
    cost: 1500,
    costType: 'cash',
    targetTableId: 'underground-dice',
    tableMultiplier: 2.0,
    hired: false,
  },
  'bouncer-vinnie': {
    id: 'bouncer-vinnie',
    name: "Vinnie 'The Brick'",
    role: "Enforcer",
    avatar: "/images/vinnie_avatar.jpg",
    description: "Keeps nosy cops and snitches away. Reduces total heat generation by 30%.",
    cost: 15000,
    costType: 'cash',
    heatReductionRate: 0.30,
    hired: false,
  },
  'dealer-marcus': {
    id: 'dealer-marcus',
    name: "Mechanic Marcus",
    role: "Card Mechanic",
    avatar: "/images/marcus_avatar.jpg",
    description: "Ensures the house rakes the biggest pots. Doubles Basement Poker earnings.",
    cost: 120000,
    costType: 'cash',
    targetTableId: 'poker-den',
    tableMultiplier: 2.0,
    hired: false,
  },
  'accountant-artie': {
    id: 'accountant-artie',
    name: "Artie 'The Ledger'",
    role: "Creative Accountant",
    avatar: "/images/artie_avatar.jpg",
    description: "Finds clever loopholes in the chip racks. +50% global chip generation.",
    cost: 4000,
    costType: 'chips',
    chipBonusRate: 1.5,
    hired: false,
  },
  'security-boris': {
    id: 'security-boris',
    name: "Boris 'The Bear'",
    role: "Chief of Security",
    avatar: "/images/vinnie_avatar.jpg",
    description: "Ex-KGB bodyguard. Reduces heat generation by 35% and defends vaults from heists.",
    cost: 450000,
    costType: 'cash',
    heatReductionRate: 0.35,
    hired: false,
  },
  'hostess-valentina': {
    id: 'hostess-valentina',
    name: "Valentina Cruz",
    role: "VIP Hostess",
    avatar: "/images/claudia_avatar.jpg",
    description: "Pours top-tier crystal cognac for high rollers. +75% Casino Floor tables revenue.",
    cost: 1800000,
    costType: 'cash',
    tableMultiplier: 1.75,
    hired: false,
  },
  'pitboss-claudia': {
    id: 'pitboss-claudia',
    name: "Claudia Vance",
    role: "Floor General",
    avatar: "/images/claudia_avatar.jpg",
    description: "Former Vegas casino manager. Boosts Roulette and Hold'em tables by 100%.",
    cost: 4500000,
    costType: 'cash',
    tableMultiplier: 2.0,
    hired: false,
  },
  'fixer-jimmy': {
    id: 'fixer-jimmy',
    name: "Jimmy 'Quick-Fix'",
    role: "Underworld Attorney",
    avatar: "/images/marcus_avatar.jpg",
    description: "Keeps a rolodex of judges and DA contacts. Reduces bribe costs by 35% and raises bribe success rate.",
    cost: 12000000,
    costType: 'cash',
    hired: false,
  },
  'math-dr-chen': {
    id: 'math-dr-chen',
    name: "Dr. Chen",
    role: "MIT Probability Savant",
    avatar: "/images/artie_avatar.jpg",
    description: "Calibrates wheel ball tracks and shoe penetration. Doubles global casino chip generation.",
    cost: 120000,
    costType: 'chips',
    chipBonusRate: 2.0,
    hired: false,
  },
  'don-lucio': {
    id: 'don-lucio',
    name: "Don Lucio",
    role: "Syndicate Kingpin",
    avatar: "/images/don_lucio_avatar.jpg",
    description: "The city council eats out of his hand. Triples all VIP Penthouse operations.",
    cost: 85000000,
    costType: 'cash',
    tableMultiplier: 3.0,
    hired: false,
  },
  'banker-helena': {
    id: 'banker-helena',
    name: "Helena von Berg",
    role: "Swiss Private Banker",
    avatar: "/images/claudia_avatar.jpg",
    description: "Routes capital through numbered alpine vaults. Doubles all front business laundering speeds.",
    cost: 2500,
    costType: 'equity',
    hired: false,
  },
  'kingpin-don-salvatore': {
    id: 'kingpin-don-salvatore',
    name: "Don Salvatore",
    role: "The Shadow Godfather",
    avatar: "/images/don_lucio_avatar.jpg",
    description: "The supreme architect of the international syndicate. Quadruples all operations across all tiers.",
    cost: 500000000,
    costType: 'cash',
    tableMultiplier: 4.0,
    hired: false,
  },
};

export const INITIAL_BUSINESSES: Record<string, FrontBusiness> = {
  'corner-carwash': {
    id: 'corner-carwash',
    name: 'Suds & Shine Auto Spa',
    type: 'Cash Front',
    description: 'Dirty bills go in with soap, clean corporate dividends come out.',
    baseCost: 7500,
    costMultiplier: 1.28,
    washRate: 20, // $20/s washed into Clean Equity
    heatSuppression: 0.15, // drops 0.15 heat per second
    level: 0,
    unlocked: false,
    unlockCost: 5000,
    accentColor: 'from-cyan-600 to-blue-500',
    iconName: 'Droplets',
  },
  'underground-boxing-gym': {
    id: 'underground-boxing-gym',
    name: 'Iron Fist Boxing Club',
    type: 'Cash Front',
    description: 'Underground prizefighting bets cash washed as membership fees.',
    baseCost: 35000,
    costMultiplier: 1.29,
    washRate: 65,
    heatSuppression: 0.25,
    level: 0,
    unlocked: false,
    unlockCost: 25000,
    accentColor: 'from-orange-600 to-amber-500',
    iconName: 'Building2',
  },
  'retro-laundromat': {
    id: 'retro-laundromat',
    name: '24/7 Spin & Tumble',
    type: 'Coin Front',
    description: 'Literally laundering cash. High volume, continuous change.',
    baseCost: 120000,
    costMultiplier: 1.30,
    washRate: 150,
    heatSuppression: 0.45,
    level: 0,
    unlocked: false,
    unlockCost: 95000,
    accentColor: 'from-teal-500 to-emerald-400',
    iconName: 'RotateCw',
  },
  'vintage-pawn-shop': {
    id: 'vintage-pawn-shop',
    name: 'Gold & Diamond Pawn',
    type: 'Goods Front',
    description: 'High-end watches and gold jewelry purchased with dirty bills and resold clean.',
    baseCost: 600000,
    costMultiplier: 1.31,
    washRate: 480,
    heatSuppression: 0.75,
    level: 0,
    unlocked: false,
    unlockCost: 450000,
    accentColor: 'from-amber-500 to-yellow-400',
    iconName: 'Building2',
  },
  'velvet-nightclub': {
    id: 'velvet-nightclub',
    name: 'Club Obsidian',
    type: 'Hospitality Front',
    description: 'Bottle service for celebrities. Perfectly justifies massive cash infusions.',
    baseCost: 2800000,
    costMultiplier: 1.33,
    washRate: 1400,
    heatSuppression: 1.20,
    level: 0,
    unlocked: false,
    unlockCost: 2200000,
    accentColor: 'from-purple-600 to-pink-500',
    iconName: 'Music',
  },
  'harbor-shipping-corp': {
    id: 'harbor-shipping-corp',
    name: 'Atlantic Cargo Shipping',
    type: 'Maritime Front',
    description: 'Container ships and port customs clearance disguise cross-border capital flow.',
    baseCost: 15000000,
    costMultiplier: 1.34,
    washRate: 4500,
    heatSuppression: 2.00,
    level: 0,
    unlocked: false,
    unlockCost: 12000000,
    accentColor: 'from-blue-600 to-cyan-500',
    iconName: 'Building2',
  },
  'offshore-holding': {
    id: 'offshore-holding',
    name: 'Cayman Apex Trust',
    type: 'Global Corporate Front',
    description: 'Layered shell companies. Heat evaporates into thin air.',
    baseCost: 80000000,
    costMultiplier: 1.36,
    washRate: 18000,
    heatSuppression: 3.50,
    level: 0,
    unlocked: false,
    unlockCost: 65000000,
    accentColor: 'from-amber-400 to-yellow-600',
    iconName: 'Building2',
  },
  'swiss-private-bank': {
    id: 'swiss-private-bank',
    name: 'Zurich Vaults Private Bank',
    type: 'Financial Front',
    description: 'Numbered encrypted bank vaults protected by Swiss sovereign banking confidentiality.',
    baseCost: 400000000,
    costMultiplier: 1.38,
    washRate: 75000,
    heatSuppression: 5.50,
    level: 0,
    unlocked: false,
    unlockCost: 320000000,
    accentColor: 'from-indigo-600 to-purple-500',
    iconName: 'Building2',
  },
  'sovereign-real-estate': {
    id: 'sovereign-real-estate',
    name: 'Sovereign Real Estate Holdings',
    type: 'Offshore Megacorp Front',
    description: 'Ultra-luxury high-rise penthouses & sovereign land portfolios laundering mega-fortunes.',
    baseCost: 2000000000,
    costMultiplier: 1.40,
    washRate: 250000,
    heatSuppression: 8.00,
    level: 0,
    unlocked: false,
    unlockCost: 1500000000,
    accentColor: 'from-blue-600 to-indigo-500',
    iconName: 'Building2',
  },
  'orbital-aerospace-corp': {
    id: 'orbital-aerospace-corp',
    name: 'AeroApex Global Charter',
    type: 'Megacorp Front',
    description: 'Private supersonic jets and orbital launch contracts operating beyond any national jurisdiction.',
    baseCost: 24000000000,
    costMultiplier: 1.42,
    washRate: 1800000,
    heatSuppression: 15.00,
    level: 0,
    unlocked: false,
    unlockCost: 18000000000,
    accentColor: 'from-cyan-400 via-sky-500 to-indigo-600',
    iconName: 'Building2',
  },
};

export const INITIAL_UPGRADES: Record<string, CasinoUpgrade> = {
  'weighted-dice': {
    id: 'weighted-dice',
    name: 'Magnetic Loaded Dice',
    category: 'Equipment',
    description: 'Gives the shooter a subtle 7 whenever the bets favor the house.',
    cost: 500,
    costType: 'cash',
    effectLabel: '+100% Cardboard Craps Revenue',
    purchased: false,
    tableId: 'underground-dice',
    multiplier: 2.0,
  },
  'card-shuffler': {
    id: 'card-shuffler',
    name: 'Silent Auto-Shuffler',
    category: 'Equipment',
    description: 'Cuts down dealer dead-time and prevents card counting.',
    cost: 4500,
    costType: 'cash',
    effectLabel: '+100% Basement Poker Revenue',
    purchased: false,
    tableId: 'poker-den',
    multiplier: 2.0,
  },
  'complimentary-whiskey': {
    id: 'complimentary-whiskey',
    name: 'Top-Shelf Bourbon',
    category: 'Hospitality',
    description: 'Keeps players feeling generous and staying longer at the tables.',
    cost: 45000,
    costType: 'cash',
    effectLabel: '+25% Global Cash Multiplier',
    purchased: false,
    globalCashMultiplier: 1.25,
  },
  'police-scanners': {
    id: 'police-scanners',
    name: 'Encrypted Police Scanners',
    category: 'Security',
    description: 'Advance warning on squad car patrols reduces heat buildup.',
    cost: 200000,
    costType: 'cash',
    effectLabel: '-25% Heat Generation',
    purchased: false,
    heatMultiplier: 0.75,
  },
  'brass-chip-molds': {
    id: 'brass-chip-molds',
    name: 'Custom Ceramic Chips',
    category: 'Equipment',
    description: 'Heavy 14g casino grade chips that players love hoarding.',
    cost: 6000,
    costType: 'chips',
    effectLabel: '+50% Global Chip Yield',
    purchased: false,
    globalChipMultiplier: 1.5,
  },
  'politician-handshake': {
    id: 'politician-handshake',
    name: 'City Hall Donations',
    category: 'Underworld',
    description: 'A discreet envelope ensures inspectors look the other way.',
    cost: 250,
    costType: 'equity',
    effectLabel: '+50% Cash & -30% Heat',
    purchased: false,
    globalCashMultiplier: 1.5,
    heatMultiplier: 0.7,
  },
  'high-speed-counters': {
    id: 'high-speed-counters',
    name: 'Optical Bill Sorters',
    category: 'Equipment',
    description: 'Sorts bundles of \$100 bills at 1,200 notes per minute.',
    cost: 1200,
    costType: 'equity',
    effectLabel: '+100% Speed to All Front Businesses',
    purchased: false,
  },
  'vault-tier-1': {
    id: 'vault-tier-1',
    name: 'Heavy Drop Safe',
    category: 'Security',
    description: 'Bolted beneath the manager desk. Protects 50% of dirty cash from police raids.',
    cost: 75000,
    costType: 'cash',
    effectLabel: 'Insures 50% Cash from Raids (Risks Heists)',
    purchased: false,
  },
  'vault-tier-2': {
    id: 'vault-tier-2',
    name: 'Reinforced Steel Walk-In',
    category: 'Security',
    description: '12-inch hardened steel door with time locks. Protects 70% of dirty cash from police raids.',
    cost: 1500000,
    costType: 'cash',
    effectLabel: 'Insures 70% Cash from Raids (Risks Heists)',
    purchased: false,
    requiresUpgradeId: 'vault-tier-1',
  },
  'vault-tier-3': {
    id: 'vault-tier-3',
    name: 'Titanium Sub-Basement Bunker',
    category: 'Security',
    description: 'Impenetrable vault sealed deep below the casino. Protects 90% of dirty cash from police raids.',
    cost: 35000000,
    costType: 'cash',
    effectLabel: 'Insures 90% Cash from Raids (Risks Heists)',
    purchased: false,
    requiresUpgradeId: 'vault-tier-2',
  },
  'microdot-cards': {
    id: 'microdot-cards',
    name: 'Infrared Marked Decks',
    category: 'Equipment',
    description: 'Dealers wear polarized lenses. Doubles Speakeasy 21 table revenue.',
    cost: 35000,
    costType: 'cash',
    effectLabel: '+100% Speakeasy 21 Revenue',
    purchased: false,
    tableId: 'speakeasy-blackjack',
    multiplier: 2.0,
  },
  'marble-track-calibrator': {
    id: 'marble-track-calibrator',
    name: 'Laser-Balanced Wheel',
    category: 'Equipment',
    description: 'Micro-calibrated ball track ensures predictable favorable bounces. Doubles Neon Roulette revenue.',
    cost: 500000,
    costType: 'cash',
    effectLabel: '+100% Neon Roulette Revenue',
    purchased: false,
    tableId: 'roulette-alley',
    multiplier: 2.0,
  },
  'private-jet-shuttle': {
    id: 'private-jet-shuttle',
    name: 'Gulfstream VIP Air Fleet',
    category: 'Hospitality',
    description: 'Private charter jet service flies international whales straight to your penthouse doors.',
    cost: 8500000,
    costType: 'cash',
    effectLabel: '+50% Global Cash Multiplier',
    purchased: false,
    globalCashMultiplier: 1.5,
  },
  'satellite-scrambler': {
    id: 'satellite-scrambler',
    name: 'Military Frequency Scramblers',
    category: 'Security',
    description: 'Jams federal surveillance vans and wiretaps. Reduces heat accumulation by 35%.',
    cost: 45000000,
    costType: 'cash',
    effectLabel: '-35% Heat Generation',
    purchased: false,
    heatMultiplier: 0.65,
  },
  'titanium-chip-vaults': {
    id: 'titanium-chip-vaults',
    name: 'Cold-Forged Titanium Chips',
    category: 'Equipment',
    description: 'Laser-engraved titanium high-roller plaques. Doubles global chip production yield.',
    cost: 45000,
    costType: 'chips',
    effectLabel: '+100% Global Chip Yield',
    purchased: false,
    globalChipMultiplier: 2.0,
  },
  'federal-judge-dinner': {
    id: 'federal-judge-dinner',
    name: 'Supreme Court Legal Retainer',
    category: 'Underworld',
    description: 'Direct federal judicial ties. -50% raid penalty damage and +25% bribe success rate.',
    cost: 4500,
    costType: 'equity',
    effectLabel: '-50% Raid Losses & +25% Bribe Success',
    purchased: false,
  },
  'crypto-mixer-servers': {
    id: 'crypto-mixer-servers',
    name: 'Quantum Blockchain Mixers',
    category: 'Equipment',
    description: 'Distributed smart-contract tumbling cleans capital at 2.5x speed across all front businesses.',
    cost: 18000,
    costType: 'equity',
    effectLabel: '+150% Laundry Washing Speed',
    purchased: false,
  },
  'vault-tier-4': {
    id: 'vault-tier-4',
    name: 'Sub-Oceanic Bunkered Vault',
    category: 'Security',
    description: 'Hydraulically sealed vault below the continental shelf. Insures 95% of dirty cash from raids.',
    cost: 250000000,
    costType: 'cash',
    effectLabel: 'Insures 95% Cash from Raids',
    purchased: false,
    requiresUpgradeId: 'vault-tier-3',
  },
  'vault-tier-5': {
    id: 'vault-tier-5',
    name: 'Orbital Satellite Deep Vault',
    category: 'Security',
    description: 'Encrypted off-planet orbital data vault. 100% raid & heist immune; dirty cash is completely untouchable.',
    cost: 2500000000,
    costType: 'cash',
    effectLabel: '100% Immuntity from Raids & Heists',
    purchased: false,
    requiresUpgradeId: 'vault-tier-4',
  },
  'syndicate-satellite-uplink': {
    id: 'syndicate-satellite-uplink',
    name: 'Global Syndicate AI Uplink',
    category: 'Underworld',
    description: 'Autonomous syndicate algorithmic coordination. Triples total revenue across all tables and businesses.',
    cost: 15000000000,
    costType: 'cash',
    effectLabel: '+200% Total Empire Production',
    purchased: false,
    globalCashMultiplier: 3.0,
  },
};

export const INITIAL_PRESTIGE_PERKS: Record<string, PrestigePerk> = {
  'mob-connections': {
    id: 'mob-connections',
    name: 'Underworld Syndicate Syndicate',
    description: 'Increases all cash revenue across all venues.',
    cost: 1,
    level: 0,
    maxLevel: 25,
    bonusType: 'globalCash',
    valuePerLevel: 0.25, // +25% per level
  },
  'whale-attractor': {
    id: 'whale-attractor',
    name: 'Vegas Whale Network',
    description: 'Brings high-stakes gamblers who drop massive stacks of chips.',
    cost: 2,
    level: 0,
    maxLevel: 20,
    bonusType: 'globalChips',
    valuePerLevel: 0.30, // +30% chips per level
  },
  'starting-bankroll': {
    id: 'starting-bankroll',
    name: 'Offshore Trust Fund',
    description: 'Start every new Strip buyout with instant capital.',
    cost: 1,
    level: 0,
    maxLevel: 10,
    bonusType: 'startingCash',
    valuePerLevel: 500, // +$500 starting cash per level
  },
  'ironclad-lawyers': {
    id: 'ironclad-lawyers',
    name: 'Retained Federal Counsel',
    description: 'Reduces heat accumulation and protects against police raids.',
    cost: 3,
    level: 0,
    maxLevel: 15,
    bonusType: 'heatResistance',
    valuePerLevel: 0.08, // -8% heat per level
  },
  'fast-wash': {
    id: 'fast-wash',
    name: 'Swift Swiss Banking',
    description: 'Accelerates the speed at which dirty cash converts to Clean Equity.',
    cost: 2,
    level: 0,
    maxLevel: 20,
    bonusType: 'launderingSpeed',
    valuePerLevel: 0.35, // +35% wash speed per level
  },
};

export const INITIAL_TOURNAMENTS: Record<string, Tournament> = {
  'downtown-freeroll': {
    id: 'downtown-freeroll',
    name: 'Downtown Speakeasy Freeroll',
    tier: 'Underground',
    description: 'A smoke-filled backroom poker shootout with local hustlers and card mechanics.',
    buyIn: 2500,
    chipsEntry: 150,
    durationSeconds: 30,
    prizePool: 18000,
    firstPlacePrize: 12000,
    chipsReward: 800,
    trophy: 'Brass Knuckle Signet',
    trophyIcon: 'Ring',
    status: 'idle',
    winChance: 0.35,
    image: '/images/table_poker.jpg',
  },
  'regional-deepstack': {
    id: 'regional-deepstack',
    name: 'Emerald Bay Deepstack',
    tier: 'Regional',
    description: 'High-stakes regional championship attracting card counters and underground bookies.',
    buyIn: 45000,
    chipsEntry: 1500,
    durationSeconds: 60,
    prizePool: 320000,
    firstPlacePrize: 220000,
    chipsReward: 8000,
    trophy: 'Emerald Diamond Ring',
    trophyIcon: 'Crown',
    status: 'idle',
    winChance: 0.30,
    image: '/images/tournament_poker_room.jpg',
  },
  'vegas-high-roller': {
    id: 'vegas-high-roller',
    name: 'Vegas High Roller Classic',
    tier: 'Championship',
    description: 'Televised championship final table with spotlights, VIP whales, and millions on the line.',
    buyIn: 1200000,
    chipsEntry: 15000,
    durationSeconds: 120,
    prizePool: 10000000,
    firstPlacePrize: 7500000,
    chipsReward: 75000,
    trophy: 'Golden Spade Bracelet',
    trophyIcon: 'Award',
    status: 'idle',
    winChance: 0.25,
    image: '/images/tournament_poker_room.jpg',
  },
  'monte-carlo-shr': {
    id: 'monte-carlo-shr',
    name: 'Monte Carlo Super High Roller',
    tier: 'High Roller',
    description: 'Ultra-exclusive private yacht invitational where offshore billionaires and world champions clash.',
    buyIn: 60000000,
    chipsEntry: 180000,
    durationSeconds: 240,
    prizePool: 550000000,
    firstPlacePrize: 400000000,
    chipsReward: 1200000,
    trophy: 'Platinum World Championship Bracelet',
    trophyIcon: 'Trophy',
    status: 'idle',
    winChance: 0.20,
    image: '/images/tournament_poker_room.jpg',
  },
  'london-mayfair-invitational': {
    id: 'london-mayfair-invitational',
    name: 'Mayfair Billionaire Invitational',
    tier: 'High Roller',
    description: 'Old-money Mayfair private club clash with European aristocrats and oil magnates.',
    buyIn: 350000000,
    chipsEntry: 1000000,
    durationSeconds: 300,
    prizePool: 3500000000,
    firstPlacePrize: 2500000000,
    chipsReward: 6000000,
    trophy: 'Mayfair Sovereign Cup',
    trophyIcon: 'Award',
    status: 'idle',
    winChance: 0.18,
    image: '/images/tournament_poker_room.jpg',
  },
  'macau-billionaire-bounty': {
    id: 'macau-billionaire-bounty',
    name: 'Macau Imperial Dragon Bounty',
    tier: 'High Roller',
    description: 'Bounty tournament with eight-figure plaques placed on the heads of international junket bosses.',
    buyIn: 2000000000,
    chipsEntry: 6000000,
    durationSeconds: 360,
    prizePool: 20000000000,
    firstPlacePrize: 15000000000,
    chipsReward: 35000000,
    trophy: 'Imperial Dragon Jade Scepter',
    trophyIcon: 'Crown',
    status: 'idle',
    winChance: 0.16,
    image: '/images/tournament_poker_room.jpg',
  },
  'dubai-royal-palace-cup': {
    id: 'dubai-royal-palace-cup',
    name: 'Dubai Royal Palace World Cup',
    tier: 'World Championship',
    description: 'High-altitude Burj penthouse final table played for sovereign oil fortunes.',
    buyIn: 15000000000,
    chipsEntry: 40000000,
    durationSeconds: 420,
    prizePool: 150000000000,
    firstPlacePrize: 100000000000,
    chipsReward: 250000000,
    trophy: 'Burj Golden Phoenix Trophy',
    trophyIcon: 'Trophy',
    status: 'idle',
    winChance: 0.14,
    image: '/images/tournament_poker_room.jpg',
  },
  'sovereign-champions-clash': {
    id: 'sovereign-champions-clash',
    name: 'Sovereign Illuminati Clash',
    tier: 'World Championship',
    description: 'The pinnacle of global poker mastery held on an offshore sovereign sanctuary.',
    buyIn: 100000000000,
    chipsEntry: 250000000,
    durationSeconds: 600,
    prizePool: 1000000000000,
    firstPlacePrize: 750000000000,
    chipsReward: 2000000000,
    trophy: 'Sovereign Illuminati Ring',
    trophyIcon: 'Sparkles',
    status: 'idle',
    winChance: 0.12,
    image: '/images/tournament_poker_room.jpg',
  },
};

export const INITIAL_PROS: Record<string, SponsoredPro> = {
  'pro-texas-slim': {
    id: 'pro-texas-slim',
    name: 'Liam Duxbury',
    alias: 'The River Assassin',
    salary: 12000,
    cutPercent: 20,
    winBonus: 0.15,
    hired: false,
    avatar: '/avatars/avatar_liam_duxbury_1772223048076.png',
    specialty: 'Aggressive street grinder who shoves any river and keeps opponents on constant tilt.',
    quote: 'Fold until you can\'t, then shove with the nuts.',
  },
  'pro-mathemagician': {
    id: 'pro-mathemagician',
    name: 'Georgina Wearing',
    alias: 'The Chip Fortress',
    salary: 90000,
    cutPercent: 15,
    winBonus: 0.25,
    hired: false,
    avatar: '/avatars/avatar_georgina_wearing_1772223035422.png',
    specialty: 'Disciplined table rock who waits for premium holdings and protects the syndicate bankroll.',
    quote: 'Emotions are noise. Stack discipline is all that exists.',
  },
  'pro-sophia': {
    id: 'pro-sophia',
    name: 'Edward Wearing',
    alias: 'All-In Syndicate Boss',
    salary: 1500000,
    cutPercent: 10,
    winBonus: 0.35,
    hired: false,
    avatar: '/avatars/avatar_edward_wearing_1772222877224.png',
    specialty: 'High-stakes mastermind who commands the table, reads physical micro-tells, and never blinks.',
    quote: 'I don\'t play the cards. I play the player.',
  },
  'pro-vladimir': {
    id: 'pro-vladimir',
    name: 'Chris Daly',
    alias: 'The Dynasty Enforcer',
    salary: 6000000,
    cutPercent: 8,
    winBonus: 0.45,
    hired: false,
    avatar: '/avatars/avatar_chris_daly_1772222942062.png',
    specialty: 'EPT championship heavyweight who crushes monster showdowns and takes down eight-figure pots.',
    quote: 'Pressure turns coal into diamonds, or crushes it to dust.',
  },
  'pro-charlotte': {
    id: 'pro-charlotte',
    name: 'Daniel Horne',
    alias: 'The Calculated Shark',
    salary: 25000000,
    cutPercent: 6,
    winBonus: 0.55,
    hired: false,
    avatar: '/avatars/avatar_daniel_horne_1772222954376.png',
    specialty: 'GTO probability virtuoso who calculates pot equity down to three decimal places.',
    quote: 'Patience, darling. Math always betrays itself.',
  },
  'pro-el-diablo': {
    id: 'pro-el-diablo',
    name: 'Stephen Flood',
    alias: 'The Shadow Fox',
    salary: 100000000,
    cutPercent: 5,
    winBonus: 0.70,
    hired: false,
    avatar: '/avatars/avatar_stephen_flood_1772223088474.png',
    specialty: 'Fearless final-table phenom whose deep deception intimidates world champions into folding.',
    quote: 'If you want my chips, you will have to bleed for every single one.',
  },
};

export const INITIAL_RELICS: Record<string, Relic> = {
  'relic-gold-nugget': {
    id: 'relic-gold-nugget',
    name: '1978 Gold Nugget Vintage Deck',
    type: 'deck',
    rarity: 'Common',
    description: 'Sealed collector casino deck from downtown vintage Vegas.',
    costChips: 1500,
    unlocked: false,
    effectDescription: '+15% Table Dirty Cash Generation',
    bonusType: 'cashMultiplier',
    bonusValue: 0.15,
    iconName: 'Layers',
  },
  'relic-loaded-dice': {
    id: 'relic-loaded-dice',
    name: 'Weighted Ivory Craps Dice',
    type: 'charm',
    rarity: 'Common',
    description: 'Shaved corners and mercury core always favor the house.',
    costChips: 4500,
    unlocked: false,
    effectDescription: '+20% Casino Chips Generation',
    bonusType: 'chipMultiplier',
    bonusValue: 0.20,
    iconName: 'Dices',
  },
  'relic-corrupt-gavel': {
    id: 'relic-corrupt-gavel',
    name: 'Magistrate\'s Polished Gavel',
    type: 'charm',
    rarity: 'Rare',
    description: 'Inscribed with favors owed by municipal judges.',
    costChips: 18000,
    unlocked: false,
    effectDescription: '+10% Commissioner Bribe Success Rate',
    bonusType: 'bribeBonus',
    bonusValue: 0.10,
    iconName: 'ShieldCheck',
  },
  'relic-swiss-ledger': {
    id: 'relic-swiss-ledger',
    name: 'Numbered Swiss Cipher Ledger',
    type: 'charm',
    rarity: 'Rare',
    description: 'Confidential encrypted bank routing codes.',
    costChips: 65000,
    unlocked: false,
    effectDescription: '-25% FBI & Police Heat Generation',
    bonusType: 'heatReduction',
    bonusValue: 0.25,
    iconName: 'BookOpen',
  },
  'relic-royal-flush': {
    id: 'relic-royal-flush',
    name: 'Solid 24k Gold Spade Deck',
    type: 'deck',
    rarity: 'Legendary',
    description: 'Custom forged for Monaco royalty. Radiates pure underworld aura.',
    costChips: 250000,
    unlocked: false,
    effectDescription: '+40% Global Cash & Chips Across All Floors',
    bonusType: 'cashMultiplier',
    bonusValue: 0.40,
    iconName: 'Crown',
  },
  'relic-lucky-horseshoe': {
    id: 'relic-lucky-horseshoe',
    name: 'Diamond Encrusted Brooch',
    type: 'charm',
    rarity: 'Legendary',
    description: 'Worn by the syndicate\'s most successful card crushers.',
    costChips: 750000,
    unlocked: false,
    effectDescription: '+20% Tournament Win Rate & Final Table Boost',
    bonusType: 'tournamentBonus',
    bonusValue: 0.20,
    iconName: 'Sparkles',
  },
  'relic-antique-chip-rack': {
    id: 'relic-antique-chip-rack',
    name: 'Antique Mahogany Chip Rack',
    type: 'charm',
    rarity: 'Rare',
    description: 'Circa-1920s mahogany rack that mysteriously keeps refilling with clay chips.',
    costChips: 1500000,
    unlocked: false,
    effectDescription: '+50% Global Chip Yield',
    bonusType: 'chipMultiplier',
    bonusValue: 0.50,
    iconName: 'Layers',
  },
  'relic-federal-pardon': {
    id: 'relic-federal-pardon',
    name: 'Signed Executive Pardon',
    type: 'charm',
    rarity: 'Legendary',
    description: 'Wax-sealed presidential pardon granting complete immunity to key syndicate operators.',
    costChips: 5000000,
    unlocked: false,
    effectDescription: '-40% FBI & Police Heat Generation',
    bonusType: 'heatReduction',
    bonusValue: 0.40,
    iconName: 'ShieldCheck',
  },
  'relic-platinum-watch': {
    id: 'relic-platinum-watch',
    name: 'Patek Diamond Tourbillon',
    type: 'charm',
    rarity: 'Rare',
    description: 'Swiss complication wristwatch worn by private bankers to synchronize international wire transfers.',
    costChips: 18000000,
    unlocked: false,
    effectDescription: '+60% Front Business Laundry Wash Speed',
    bonusType: 'laundrySpeed',
    bonusValue: 0.60,
    iconName: 'Sparkles',
  },
  'relic-ruby-seal': {
    id: 'relic-ruby-seal',
    name: 'Imperial Habsburg Ruby Seal',
    type: 'deck',
    rarity: 'Legendary',
    description: 'Blood-red signet stamp authorizing unlimited credit lines at any European casino.',
    costChips: 60000000,
    unlocked: false,
    effectDescription: '+75% Table Dirty Cash Generation',
    bonusType: 'cashMultiplier',
    bonusValue: 0.75,
    iconName: 'Gem',
  },
  'relic-black-lotus': {
    id: 'relic-black-lotus',
    name: 'Sovereign Black Lotus Card',
    type: 'deck',
    rarity: 'Mythic',
    description: 'One-of-a-kind underworld artifact that bends tournament probabilities in your favor.',
    costChips: 250000000,
    unlocked: false,
    effectDescription: '+35% Tournament Win Rate & Payout Boost',
    bonusType: 'tournamentBonus',
    bonusValue: 0.35,
    iconName: 'Crown',
  },
  'relic-crown-jewel': {
    id: 'relic-crown-jewel',
    name: 'Eye of Macau Blue Diamond',
    type: 'charm',
    rarity: 'Mythic',
    description: 'The legendary 95-carat flawless blue diamond. Radiates supreme underworld dominance.',
    costChips: 1000000000,
    unlocked: false,
    effectDescription: '+150% Global Cash Production Across All Venues',
    bonusType: 'cashMultiplier',
    bonusValue: 1.50,
    iconName: 'Sparkles',
  },
};

export const INITIAL_DISTRICTS: Record<string, District> = {
  'downtown': {
    id: 'downtown',
    name: 'Downtown Neon Alley',
    tagline: 'The Underground Syndicate Seed',
    description: 'Smoky backrooms, alley craps tables, and dim speakeasies. High street heat but humble beginnings.',
    unlockCostCash: 0,
    unlockCostEquity: 0,
    unlocked: true,
    revenueMultiplier: 1.0,
    heatModifier: 1.0,
    bossName: 'Street Hustlers',
    accentColor: 'from-amber-600 to-yellow-500',
    image: '/images/hero_dealer_desk.jpg',
  },
  'vegas': {
    id: 'vegas',
    name: 'The Las Vegas Strip',
    tagline: 'Glitz, Glamour & High Rollers',
    description: 'Palatial resorts, mega-casinos, and convention centers. Doubles all table revenue with massive chip volumes.',
    unlockCostCash: 5000000,
    unlockCostEquity: 500,
    unlocked: false,
    revenueMultiplier: 2.0,
    heatModifier: 1.15,
    bossName: 'Don Lucio',
    accentColor: 'from-gold to-amber-500',
    image: '/images/vegas_strip_resort.jpg',
  },
  'macau': {
    id: 'macau',
    name: 'Macau Cotai Bay',
    tagline: 'The VIP Whale Capital',
    description: 'High-volume private baccarat salons where billionaires wager tens of millions per hand. 4x Revenue.',
    unlockCostCash: 250000000,
    unlockCostEquity: 4000,
    unlocked: false,
    revenueMultiplier: 4.0,
    heatModifier: 1.30,
    bossName: 'Golden Dragon Triad',
    accentColor: 'from-emerald-500 to-teal-400',
    image: '/images/tournament_poker_room.jpg',
  },
  'monaco': {
    id: 'monaco',
    name: 'Monaco Yacht Harbor',
    tagline: 'Untouchable Sovereign Haven',
    description: 'Offshore superyachts anchored under Mediterranean stars. Zero street heat, protected by diplomatic immunity. 10x Revenue.',
    unlockCostCash: 15000000000,
    unlockCostEquity: 40000,
    unlocked: false,
    revenueMultiplier: 10.0,
    heatModifier: 0.50,
    bossName: 'The Sovereign Circle',
    accentColor: 'from-cyan-400 to-blue-600',
    image: '/images/vintage_relic_vault.jpg',
  },
  'london-mayfair': {
    id: 'london-mayfair',
    name: 'London Mayfair Enclave',
    tagline: 'Old Money Aristocrat Salons',
    description: 'Private 18th-century Georgian clubhouses for dukes, royalty, and international financiers. 20x Revenue.',
    unlockCostCash: 100000000000,
    unlockCostEquity: 250000,
    unlocked: false,
    revenueMultiplier: 20.0,
    heatModifier: 0.60,
    bossName: 'Lord Kensington',
    accentColor: 'from-indigo-600 to-purple-500',
    image: '/images/tournament_poker_room.jpg',
  },
  'singapore-marina': {
    id: 'singapore-marina',
    name: 'Singapore Marina Bay',
    tagline: 'High-Tech Sovereign Skygardens',
    description: 'Quantum encrypted financial networks and sky-high infinity pools catering to Asian tech billionaires. 45x Revenue.',
    unlockCostCash: 1000000000000,
    unlockCostEquity: 2000000,
    unlocked: false,
    revenueMultiplier: 45.0,
    heatModifier: 0.40,
    bossName: 'Chairman Chen',
    accentColor: 'from-teal-500 to-emerald-400',
    image: '/images/vegas_strip_resort.jpg',
  },
  'dubai-palm': {
    id: 'dubai-palm',
    name: 'Dubai Palm Jumeirah',
    tagline: 'Gilded Sanctuaries of Gold & Oil',
    description: 'Palatial artificial islands of marble and 24k gold. Sovereign wealth funds wager sovereign debts. 100x Revenue.',
    unlockCostCash: 15000000000000,
    unlockCostEquity: 25000000,
    unlocked: false,
    revenueMultiplier: 100.0,
    heatModifier: 0.30,
    bossName: 'Sheikh Al-Fahad',
    accentColor: 'from-gold to-yellow-300',
    image: '/images/tournament_poker_room.jpg',
  },
  'sovereign-orbit': {
    id: 'sovereign-orbit',
    name: 'The Orbital Sovereign Station',
    tagline: 'Zero-Gravity Extraterritorial Sanctuary',
    description: 'Low-Earth orbit mega-station completely exempt from terrestrial treaties and sovereign laws. 250x Revenue.',
    unlockCostCash: 100000000000000,
    unlockCostEquity: 200000000,
    unlocked: false,
    revenueMultiplier: 250.0,
    heatModifier: 0.10,
    bossName: 'The Architect',
    accentColor: 'from-cyan-400 via-purple-500 to-rose-500',
    image: '/images/vintage_relic_vault.jpg',
  },
};

export const INITIAL_ACHIEVEMENTS: Record<string, Achievement> = {
  'ach-first-deal': {
    id: 'ach-first-deal',
    title: 'First Cut of the Deck',
    category: 'Wealth',
    description: 'Deal your first active hand at the Boss Desk.',
    rewardTokens: 1,
    unlocked: false,
    claimed: false,
    iconName: 'Play',
  },
  'ach-hundred-grand': {
    id: 'ach-hundred-grand',
    title: 'Six-Figure Syndicate',
    category: 'Wealth',
    description: 'Accumulate $100,000 in dirty cash bankroll.',
    rewardTokens: 2,
    unlocked: false,
    claimed: false,
    iconName: 'DollarSign',
  },
  'ach-millionaire': {
    id: 'ach-millionaire',
    title: 'Vegas High Roller',
    category: 'Wealth',
    description: 'Amass $1,000,000 dirty cash reserves.',
    rewardTokens: 5,
    unlocked: false,
    claimed: false,
    iconName: 'Coins',
  },
  'ach-clean-sheets': {
    id: 'ach-clean-sheets',
    title: 'Clean As A Whistle',
    category: 'Empire',
    description: 'Launder 500 Clean Corporate Equity (💎).',
    rewardTokens: 3,
    unlocked: false,
    claimed: false,
    iconName: 'Gem',
  },
  'ach-snitch-catcher': {
    id: 'ach-snitch-catcher',
    title: 'Loose Lips Sink Ships',
    category: 'Underworld',
    description: 'Interrogate an undercover police snitch before they escape.',
    rewardTokens: 2,
    unlocked: false,
    claimed: false,
    iconName: 'UserX',
  },
  'ach-bribe-king': {
    id: 'ach-bribe-king',
    title: 'Friends in High Places',
    category: 'Underworld',
    description: 'Successfully bribe the police commissioner to drop heat.',
    rewardTokens: 3,
    unlocked: false,
    claimed: false,
    iconName: 'ShieldAlert',
  },
  'ach-tourney-champ': {
    id: 'ach-tourney-champ',
    title: 'First Place Finish',
    category: 'Poker',
    description: 'Win 1st place in an underground or regional poker tournament.',
    rewardTokens: 5,
    unlocked: false,
    claimed: false,
    iconName: 'Trophy',
  },
  'ach-pro-sponsor': {
    id: 'ach-pro-sponsor',
    title: 'The Staker',
    category: 'Poker',
    description: 'Recruit your first sponsored tournament pro to your stable.',
    rewardTokens: 2,
    unlocked: false,
    claimed: false,
    iconName: 'Users',
  },
  'ach-relic-collector': {
    id: 'ach-relic-collector',
    title: 'Relic Appraiser',
    category: 'Empire',
    description: 'Equip 3 active relics simultaneously on your vault pedestals.',
    rewardTokens: 4,
    unlocked: false,
    claimed: false,
    iconName: 'Layers',
  },
  'ach-vegas-strip': {
    id: 'ach-vegas-strip',
    title: 'Strip Takeover',
    category: 'Empire',
    description: 'Unlock The Las Vegas Strip district.',
    rewardTokens: 8,
    unlocked: false,
    claimed: false,
    iconName: 'MapPin',
  },
  'ach-billionaire': {
    id: 'ach-billionaire',
    title: 'Billion Dollar Empire',
    category: 'Wealth',
    description: 'Amass $1,000,000,000 dirty cash bankroll reserves.',
    rewardTokens: 10,
    unlocked: false,
    claimed: false,
    iconName: 'DollarSign',
  },
  'ach-trillionaire': {
    id: 'ach-trillionaire',
    title: 'Trillionaire Oligarch',
    category: 'Wealth',
    description: 'Amass $1,000,000,000,000 dirty cash in your underworld vault.',
    rewardTokens: 25,
    unlocked: false,
    claimed: false,
    iconName: 'Crown',
  },
  'ach-clean-mogul': {
    id: 'ach-clean-mogul',
    title: 'Clean Corporate Mogul',
    category: 'Empire',
    description: 'Launder 50,000 Clean Corporate Equity (💎).',
    rewardTokens: 15,
    unlocked: false,
    claimed: false,
    iconName: 'Gem',
  },
  'ach-mayfair-club': {
    id: 'ach-mayfair-club',
    title: 'Mayfair High Society',
    category: 'Empire',
    description: 'Unlock the prestigious London Mayfair Enclave district.',
    rewardTokens: 12,
    unlocked: false,
    claimed: false,
    iconName: 'Building2',
  },
  'ach-orbital-haven': {
    id: 'ach-orbital-haven',
    title: 'Above the Law',
    category: 'Empire',
    description: 'Unlock The Orbital Sovereign Station district.',
    rewardTokens: 50,
    unlocked: false,
    claimed: false,
    iconName: 'Sparkles',
  },
  'ach-super-high-roller': {
    id: 'ach-super-high-roller',
    title: 'World Champion',
    category: 'Poker',
    description: 'Win 1st place in the Monte Carlo Super High Roller.',
    rewardTokens: 20,
    unlocked: false,
    claimed: false,
    iconName: 'Trophy',
  },
  'ach-pro-stable': {
    id: 'ach-pro-stable',
    title: 'Championship Stable',
    category: 'Poker',
    description: 'Sponsor all 6 professional tournament players simultaneously.',
    rewardTokens: 15,
    unlocked: false,
    claimed: false,
    iconName: 'Users',
  },
  'ach-relic-hoarder': {
    id: 'ach-relic-hoarder',
    title: 'Master Antiquarian',
    category: 'Empire',
    description: 'Equip 5 active relics simultaneously on your vault pedestals.',
    rewardTokens: 20,
    unlocked: false,
    claimed: false,
    iconName: 'Layers',
  },
  'ach-first-reset': {
    id: 'ach-first-reset',
    title: 'Strip Buyout Pioneer',
    category: 'Underworld',
    description: 'Execute your first Strip Buyout prestige reset.',
    rewardTokens: 10,
    unlocked: false,
    claimed: false,
    iconName: 'Flame',
  },
  'ach-shadow-cartel': {
    id: 'ach-shadow-cartel',
    title: 'Illuminati Puppetmaster',
    category: 'Underworld',
    description: 'Reach Prestige Reset Tier 3 and appoint a Shadow Cabinet official.',
    rewardTokens: 30,
    unlocked: false,
    claimed: false,
    iconName: 'Crown',
  },
};

export const INITIAL_SPORTSBOOK_MATCHES: SportsbookMatch[] = [
  {
    id: 'match-boxing-title',
    sport: 'Boxing',
    eventTitle: 'World Heavyweight Championship',
    teamA: 'Marcus "The Iron" Cole',
    teamB: 'Dmitri "The Bear" Volkov',
    oddsA: 1.65,
    oddsB: 2.30,
    status: 'open',
    endsAt: Date.now() + 45000,
  },
  {
    id: 'match-derby-sprint',
    sport: 'Horse Racing',
    eventTitle: 'Churchill Downs Invitational',
    teamA: 'Midnight Sovereign (No. 4)',
    teamB: 'Lucky Strike (No. 7)',
    oddsA: 1.85,
    oddsB: 1.95,
    status: 'open',
    endsAt: Date.now() + 90000,
  },
  {
    id: 'match-premier-derby',
    sport: 'Football',
    eventTitle: 'European Champions Cup Final',
    teamA: 'Madrid Royals',
    teamB: 'London Knights',
    oddsA: 2.10,
    oddsB: 1.75,
    status: 'open',
    endsAt: Date.now() + 150000,
  },
];

export const INITIAL_BLACK_MARKET_CONTRACTS: Record<string, BlackMarketContract> = {
  'contract-iron-pipeline': {
    id: 'contract-iron-pipeline',
    name: 'Ironclad Distribution Pipeline',
    codename: 'PROJECT VULCAN',
    description: 'Underworld supply route bypasses state tariffs and dealer cuts. Permanent +50% Cash Revenue across all tables.',
    costTokens: 5,
    costEquity: 1000,
    unlocked: false,
    category: 'Operations',
    effectLabel: '+50% Cash Revenue Across All Tables',
    iconName: 'Coins',
  },
  'contract-diplomatic-pouch': {
    id: 'contract-diplomatic-pouch',
    name: 'Diplomatic Immunity Courier',
    codename: 'OPERATION COURIER',
    description: 'Consular pouches transport dirty bankrolls without customs or police scrutiny. Cuts all heat buildup in half permanently.',
    costTokens: 8,
    costEquity: 2500,
    unlocked: false,
    category: 'Bribery',
    effectLabel: '-50% Heat Accumulation Everywhere',
    iconName: 'ShieldAlert',
  },
  'contract-cayman-routing': {
    id: 'contract-cayman-routing',
    name: 'Cayman Quantum Wire Routing',
    codename: 'OFFSHORE GHOST',
    description: 'Autonomous financial script layers transactions through 50 shell corporations per millisecond. Doubles all laundry washing speed.',
    costTokens: 10,
    costEquity: 5000,
    unlocked: false,
    category: 'Laundering',
    effectLabel: '+100% Laundering Wash Speed',
    iconName: 'Building2',
  },
  'contract-whale-consortium': {
    id: 'contract-whale-consortium',
    name: 'Global High-Roller Junket',
    codename: 'PROJECT LEVIATHAN',
    description: 'Direct VIP junket flights transport billionaire foreign gamblers directly to your casino floor. Doubles chip drop yield everywhere.',
    costTokens: 12,
    costEquity: 10000,
    unlocked: false,
    category: 'VIP',
    effectLabel: '+100% Global Chips Drop Yield',
    iconName: 'Crown',
  },
  'contract-interpol-ghost': {
    id: 'contract-interpol-ghost',
    name: 'Interpol Data Purge',
    codename: 'GHOST PROTOCOL',
    description: 'Federal databases erase your syndicate identities automatically. Police raids never seize dirty cash reserves.',
    costTokens: 20,
    costEquity: 50000,
    unlocked: false,
    category: 'Bribery',
    effectLabel: 'Police Raids Seize 0% Dirty Cash',
    iconName: 'ShieldCheck',
  },
  'contract-syndicate-bailout': {
    id: 'contract-syndicate-bailout',
    name: 'Underworld Sovereign Trust',
    codename: 'PROJECT OMEGA',
    description: 'Sovereign offshore syndicate guarantees a massive $10,000,000 cash grant at the start of every future Strip Buyout.',
    costTokens: 15,
    costEquity: 25000,
    unlocked: false,
    category: 'Operations',
    effectLabel: '+$10M Starting Cash on Every Reset',
    iconName: 'Sparkles',
  },
};

export const INITIAL_HEIST_MISSIONS: Record<string, HeistMission> = {
  'heist-rival-vault': {
    id: 'heist-rival-vault',
    targetName: 'Downtown Cartel Stash House',
    targetType: 'Rival Mafia Vault',
    description: 'Raid an unguarded rival syndicate cash counting house in the industrial district.',
    cashReward: 500000000,
    tokensReward: 5,
    heatPenalty: 25,
    durationSeconds: 120,
    riskPercent: 25,
    status: 'ready',
  },
  'heist-federal-reserve-truck': {
    id: 'heist-federal-reserve-truck',
    targetName: 'Federal Armored Transport',
    targetType: 'Federal Reserve Truck',
    description: 'Ambush a heavily armored convoy transporting minted bills between regional central reserves.',
    cashReward: 5000000000,
    tokensReward: 15,
    heatPenalty: 40,
    durationSeconds: 300,
    riskPercent: 35,
    status: 'ready',
  },
  'heist-swiss-depository': {
    id: 'heist-swiss-depository',
    targetName: 'Zurich Central Depository',
    targetType: 'Swiss Depository',
    description: 'Infiltrate the Alpine subterranean vault housing unrecorded bond certificates and bullion.',
    cashReward: 50000000000,
    tokensReward: 40,
    heatPenalty: 50,
    durationSeconds: 600,
    riskPercent: 45,
    status: 'ready',
  },
  'heist-monaco-megayacht': {
    id: 'heist-monaco-megayacht',
    targetName: 'Sovereign Prince Mega-Yacht Safe',
    targetType: 'Megayacht Safe',
    description: 'Execute a silent sea boarding during a high-society masquerade ball in international waters.',
    cashReward: 500000000000,
    tokensReward: 100,
    heatPenalty: 60,
    durationSeconds: 1200,
    riskPercent: 55,
    status: 'ready',
  },
};

export const INITIAL_SHADOW_CABINET: Record<string, ShadowCabinetOfficial> = {
  'cabinet-attorney-general': {
    id: 'cabinet-attorney-general',
    officeName: 'Federal Attorney General',
    incumbent: 'Judge Arthur Vance',
    description: 'Controls the Department of Justice docket. Cuts raid frequency by 70% and cuts commissioner bribe costs by 50%.',
    costEquity: 100000,
    bribed: false,
    benefitLabel: '-70% Police Raids & -50% Bribe Costs',
    iconName: 'ShieldCheck',
  },
  'cabinet-treasury-secretary': {
    id: 'cabinet-treasury-secretary',
    officeName: 'Treasury Secretary',
    incumbent: 'Madame Eleanor Vance',
    description: 'Oversees FinCEN and currency printing. Triples Clean Equity laundering conversion rate.',
    costEquity: 250000,
    bribed: false,
    benefitLabel: '+200% Laundering Clean Equity Conversion',
    iconName: 'Gem',
  },
  'cabinet-central-banker': {
    id: 'cabinet-central-banker',
    officeName: 'Central Bank Governor',
    incumbent: 'Governor Julian Sterling',
    description: 'Dictates prime interest rates and liquidity injections. Quadruples cash generation across all 18 tables.',
    costEquity: 750000,
    bribed: false,
    benefitLabel: '4x Global Cash Revenue on All Tables',
    iconName: 'Coins',
  },
  'cabinet-interpol-director': {
    id: 'cabinet-interpol-director',
    officeName: 'INTERPOL Director General',
    incumbent: 'Director Henri Laurent',
    description: 'Commands international red notices. Grants complete immunity from FBI interventions and +25% Heist Success Rate.',
    costEquity: 2000000,
    bribed: false,
    benefitLabel: 'FBI Immunity & +25% Heist Success Rate',
    iconName: 'Crown',
  },
};

export const LUCKY_WHEEL_WEDGES: WheelReward[] = [
  { id: 'wheel-cash-small', label: '$5,000,000 Dirty Cash', type: 'cash', value: 5000000, color: '#10b981' },
  { id: 'wheel-chips-1', label: '25,000 Casino Chips', type: 'chips', value: 25000, color: '#3b82f6' },
  { id: 'wheel-equity-1', label: '1,000 Clean Equity', type: 'equity', value: 1000, color: '#06b6d4' },
  { id: 'wheel-tokens-1', label: '10 Syndicate Tokens', type: 'tokens', value: 10, color: '#f59e0b' },
  { id: 'wheel-cash-huge', label: '$50,000,000 Dirty Cash', type: 'cash', value: 50000000, color: '#10b981' },
  { id: 'wheel-chips-2', label: '100,000 Casino Chips', type: 'chips', value: 100000, color: '#8b5cf6' },
  { id: 'wheel-equity-2', label: '5,000 Clean Equity', type: 'equity', value: 5000, color: '#ec4899' },
  { id: 'wheel-jackpot', label: 'JACKPOT: 50 Tokens + $250M', type: 'tokens', value: 50, color: '#eab308' },
];

export const DEFAULT_GAME_STATE: GameState = {
  version: 2,
  cash: 50, // Starting seed capital
  chips: 10,
  equity: 0,
  heat: 0,
  mobTokens: 0,
  reputation: 1,

  tables: INITIAL_TABLES,
  staff: INITIAL_STAFF,
  upgrades: INITIAL_UPGRADES,
  businesses: INITIAL_BUSINESSES,
  perks: INITIAL_PRESTIGE_PERKS,

  stats: {
    totalClicks: 0,
    handsWon: 0,
    blackjacksHit: 0,
    totalCashEarned: 50,
    totalChipsEarned: 10,
    totalLaundered: 0,
    equityEarnedThisRun: 0,
    totalEquityEarned: 0,
    raidsAvoided: 0,
    prestigeResets: 0,
    timePlayedSeconds: 0,
  },
  settings: {
    soundEnabled: true,
    scientificNotation: false,
    particlesEnabled: true,
  },
  lastSaveTime: Date.now(),
  lastTickTime: Date.now(),

  vaultLevel: 0,
  padlockedTables: {},
  detainedStaff: {},
  activeTableBoosts: {},
  activeFloorEvent: null,
  lastFloorEventCheckTime: Date.now(),

  // Expanded Systems
  tournaments: INITIAL_TOURNAMENTS,
  sponsoredPros: INITIAL_PROS,
  wonTrophies: [],
  sportsbookMatches: INITIAL_SPORTSBOOK_MATCHES,
  totalVigCollected: 0,
  relics: INITIAL_RELICS,
  equippedRelicIds: [],
  currentDistrictId: 'downtown',
  districts: INITIAL_DISTRICTS,
  achievements: INITIAL_ACHIEVEMENTS,

  // Post-Reset Systems
  blackMarketContracts: INITIAL_BLACK_MARKET_CONTRACTS,
  lastWheelSpinTime: 0,
  heistMissions: INITIAL_HEIST_MISSIONS,
  shadowCabinet: INITIAL_SHADOW_CABINET,
};
